name = "ModuleDocstrings"
uuid = "982ee2ff-df44-427b-be98-c6c9fd49f925"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Example", "Pkg", "Test"]
